#    ░█▄█░█▀█░▀█▀░█░█░█▀▀░█▀▀░█▀█░░░░░░░░░█░█░█▀█░█░░░░░░░░░░░█▀█░█░░░█▀█░█▀▀░█▀▄░▀█▀░▀█▀░▀█▀░█░█
#    ░█░█░█▀█░░█░░█░█░█░█░█▀▀░█░█░░░▄█▄░░░█▄█░█▀█░█░░░░░▄▄▄░░░█▀█░█░░░█▀█░█░░░█▀▄░░█░░░█░░░█░░░█░
#    ░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░░▀░░░░▀░▀░▀░▀░▀▀▀░░░░░░░░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░░▀░░░▀░

[colors.primary]
background = "#1a1111"
foreground = "#f0dedd"
dim_foreground = "#a08c8b"
bright_foreground = "#f0dedd"

[colors.cursor]
text = "#f0dedd"
cursor = "#d7c1c0"

[colors.vi_mode_cursor]
text = "#1a1111"
cursor = "#ffb3b0"

[colors.search.matches]
foreground = "#534342"
background = "#e3c28c"

[colors.search.focused_match]
foreground = "#534342"
background = "#ffb3b0"

[colors.footer_bar]
foreground = "#534342"
background = "#f0dedd"

[colors.hints.start]
foreground = "#534342"
background = "#e6bdbb"

[colors.hints.end]
foreground = "#534342"
background = "#e6bdbb"

[colors.selection]
text = "#1a1111"
background = "#ffb3b0"

[colors.normal]
black = "{color0}"
red = "{color1}"
green = "{color2}"
yellow = "{color3}"
blue = "{color4}"
magenta = "{color5}"
cyan = "{color6}"
white = "{color7}"

[colors.bright]
black = "{color8}"
red = "{color9}"
green = "{color10}"
yellow = "{color11}"
blue = "{color12}"
magenta = "{color13}"
cyan = "{color14}"
white = "{color15}"

[colors.dim]
black = "{color15}"
red = "{color9}"
green = "{color13}"
yellow = "{color11}"
blue = "{color12}"
magenta = "{color10}"
cyan = "{color14}"
white = "{color8}"

[[colors.indexed_colors]]
index = 16
color = "#e6bdbb"

[[colors.indexed_colors]]
index = 17
color = "#e3c28c"
