#    ░█▄█░█▀█░▀█▀░█░█░█▀▀░█▀▀░█▀█░░░░░░░░░█░█░█▀█░█░░░░░░░░░░░█▀█░█░░░█▀█░█▀▀░█▀▄░▀█▀░▀█▀░▀█▀░█░█
#    ░█░█░█▀█░░█░░█░█░█░█░█▀▀░█░█░░░▄█▄░░░█▄█░█▀█░█░░░░░▄▄▄░░░█▀█░█░░░█▀█░█░░░█▀▄░░█░░░█░░░█░░░█░
#    ░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░░▀░░░░▀░▀░▀░▀░▀▀▀░░░░░░░░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░░▀░░░▀░

[colors.primary]
background = "#121318"
foreground = "#e2e2e9"
dim_foreground = "#121318"
bright_foreground = "#e2e2e9"

[colors.cursor]
text = "#e2e2e9"
cursor = "#c5c6d0"

[colors.vi_mode_cursor]
text = "#121318"
cursor = "#b1c5ff"

[colors.search.matches]
foreground = "#44464f"
background = "#e0bbdd"

[colors.search.focused_match]
foreground = "#44464f"
background = "#b1c5ff"

[colors.footer_bar]
foreground = "#44464f"
background = "#e2e2e9"

[colors.hints.start]
foreground = "#44464f"
background = "#c0c6dc"

[colors.hints.end]
foreground = "#44464f"
background = "#c0c6dc"

[colors.selection]
text = "#121318"
background = "#b1c5ff"

[colors.normal]
black = "#0d101f"
red = "#75503f"
green = "#38518d"
yellow = "#53697a"
blue = "#576ba5"
magenta = "#898799"
cyan = "#6f7ead"
white = "#90929b"

[colors.bright]
black = "#5c6071"
red = "#9D6B54"
green = "#4B6CBC"
yellow = "#6F8DA3"
blue = "#758FDD"
magenta = "#B7B5CC"
cyan = "#95A8E7"
white = "#c2c3c7"

[colors.dim]
black = "#c2c3c7"
red = "#9D6B54"
green = "#B7B5CC"
yellow = "#6F8DA3"
blue = "#758FDD"
magenta = "#4B6CBC"
cyan = "#95A8E7"
white = "#5c6071"

[[colors.indexed_colors]]
index = 16
color = "#c0c6dc"

[[colors.indexed_colors]]
index = 17
color = "#e0bbdd"
